openapi: 3.0.3
tags:
  - name: partner
  - name: permissions
info:
  title: partner-api
  version: v2.0
  description: Europaces partner management allows organizations to map their own structure to give each partner or employee access and set rights.
  contact:
    name: Europace AG
    url: 'https://docs.api.europace.de'
    email: info@europace.de
  termsOfService: 'https://docs.api.europace.de/nutzungsbedingungen/'
servers:
  - url: 'https://api.europace.de/v2'
    description: Produktion Server
paths:
  '/partner/{partnerId}':
    get:
      summary: get partner data
      operationId: getPartner
      description: |
        Provides the data of a partner.

        Requirements:
        * OAuth token has scope `partner:plakette:lesen`.
        * To access a partner, the caller basically needs permission to see it. This right exists if the retrieved partner is below the authenticated partner in the hierarchy or the Einstellungsrecht is assigned to the authenticated partner.
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      tags:
        - Partner
    patch:
      summary: update partner data
      operationId: updatePartner
      description: |
        update partner data

        This overwrites **only** those attributes that are included in the PATCH request. All other attributes are not changed.

        Requirements:
        * OAuth token has the scope `partner:plakette:schreiben`.
        * Caller has Einstellungsrechte on the partner

        ### Attributes that can be changed via PATCH
        - anrede
        - anschrift
        - aufsichtsbehoerde
        - bankverbindung
        - email
        - externePartnerId
        - faxnummer
        - firmenname
        - firmennameZusatz
        - geburtsdatum
        - kreditsachbearbeiter
        - mobilnummer
        - name
        - vorname
        - nachname
        - registrierungsnummer
        - telefonnummer
        - titelFunktion
        - webseite
      security:
        - europace_oauth2:
            - 'partner:plakette:schreiben'
      tags:
        - Partner
  '/partner/{partnerId}/kontaktdaten':
    get:
      summary: get contact details
      operationId: getKontaktdaten
      description: |
        Provides the contact details of a partner if you have access to him or a trade relationship.

        The contact details of partners are provided in order to be able to work together.

        Requirements:
        * the caller has a trading relationship with the partner
        and/or
        * the caller has an [Zugriffsrecht](https://docs.api.europace.de/common/glossary/) to the partner
        and/or
        * the caller has a [Einstellungsrecht](https://docs.api.europace.de/common/glossary/) to the partner
        and/or
        * the caller is above the partner in the hierarchy
      tags:
        - Partner
  '/partner/{partnerId}/rechte':
    get:
      summary: get user permissions
      operationId: getPartnerRechte
      description: |-
        Provides the permissions of a user.

        Requirements:
        * OAuth token has scope partner:plakette:lesen
        * To access a partner, the caller basically needs permission to see it. This right exists if the retrieved partner is below the authenticated partner in the hierarchy or the Einstellungsrecht is assigned to the authenticated partner.
      security:
        - europace_oauth2:
            - 'partner:rechte:lesen'
      tags:
        - Partner
        - Rechte
    patch:
      summary: set user permissions
      operationId: setPartnerRecht
      description: |-
        Update permissions of a user.

        Requirements:
        * OAuth token has the scope `partner:rechte:schreiben`.
        * Caller has a [Einstellungsrecht](https://docs.api.europace.de/common/glossary/) on the partner
      security:
        - europace_oauth2:
            - 'partner:rechte:schreiben'
      tags:
        - Partner
  '/partner/{partnerId}/untergeordnete':
    post:
      summary: create partner
      operationId: createPartner
      description: |-
        Creates a new partner as an organization or person, depending on the type.

        Creating a new partner is always done below an existing partner:
        `https://api.europace.de/v2/partner/{PartnerId}/untergeordnete`

        Requirements:
        * OAuth token has scope `partner:plakette:anlegen`.
        * Caller is a partner of type Person
        * Caller has the `may create organizational units` permission. 
        * Caller has [Einstellungsrechte](https://docs.api.europace.de/common/glossary/) on the partner under which the new partner is to be created

        The following rules apply to server-side evaluation:

        - unknown attributes are ignored.
        - For organizations, person-specific attributes are ignored.
        - For persons, organization-specific attributes are ignored.
        - Empty attributes for strings ("") are ignored.
        - "partnerId" cannot be set and will be ignored.
        - Rights are set to false for persons if not specified.

        > **Note**
        > 
        > For a successful offer acceptance in BaufiSmart it is necessary for the following processes that the following attributes are maintained in the partner management for the account manager of the transaction:
        > - anrede
        > - vorname
        > - nachname
        > - anschrift
        > - bankverbindung
        > - email
      security:
        - europace_oauth2:
            - 'partner:plakette:anlegen'
      tags:
        - Partner
    get:
      summary: get subordinate partners
      operationId: getChildren
      description: Returns a list of child partners.
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      tags:
        - Partner
        - Rechte
  '/partner/{partnerId}/partnerkennzeichen':
    get:
      summary: get partner code
      operationId: getPartnerkennzeichen
      description: |-
        The partner codes identify a sales organisation at a loan provider. The recorded values can be read out with this endpoint. The specific value for a loan provider will be delivered in the Antraege-API to him. This endpoint is for managing purpose.

        Requirements:
        * OAuth token has scope `partner:plakette:lesen `
        * To access a partner, the caller basically needs permission to see it. This right exists if the retrieved partner is below the authenticated partner in the hierarchy or the Einstellungsrecht is assigned to the authenticated partner.
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      tags:
        - Partner
  '/partner/{partnerId}/administrierbare':
    get:
      summary: get setting right
      operationId: getAdministrierbare
      tags:
        - Partner
        - Rechte
      description: |-
        Returns all partners for which this partner is allowed to change the data and authorizations or retrieve the reporting.

        At least the partner itself is returned, since everyone may at least set itself or retrieve its own reporting.

        In order to achieve a better performance, the implicitly administrable partners have been omitted in the partner-api. To determine these, it is necessary to iterate over the subordinates of the result list.

        Requirements:
        * OAuth token has scope `partner:plakette:lesen`.
        * Each partner may make changes to himself or other partners if he has the [Einstellungsrecht](https://docs.api.europace.de/common/glossary/). This means that partner data or authorizations can be adjusted. Authorizations can only be assigned if the executing partner has them himself.
      security:
        - europace_oauth2:
            - 'partner:beziehungen:lesen'
  '/partner/{partnerId}/uebernehmbare':
    get:
      summary: get access rights
      operationId: getUebernehmbare
      tags:
        - Partner
        - Rechte
      description: |-
        The [Zugriffrecht](https://docs.api.europace.de/common/glossary/) entitles partners to read and write access to all [Vorgänge](https://docs.api.europace.de/common/glossary/) of another partner.

        In order to achieve better performance, the partner-api does not output the implicitly acceptable ones. To determine these, it is necessary to iterate over the subordinates of the result list.

        * OAuth token has scope `partner:rechte:lesen `
        * To access a partner, the caller basically needs permission to see it. This right exists if the retrieved partner is below the authenticated partner in the hierarchy or the Einstellungsrecht is assigned to the authenticated partner.
      security:
        - europace_oauth2:
            - 'partner:beziehungen:lesen'
  '/partner/{partnerId}/uebernahmeRechtFuer/{target}':
    get:
      summary: check access right
      operationId: getUebernahmeRechtFuer
      tags:
        - Partner
        - Rechte
      description: |-
        Determines whether the partner is allowed to access the operations of another partner.
        Do I have access to Partner XYZ15?

        The [Zugriffrecht](https://docs.api.europace.de/common/glossary/) entitles partners to read and write access to all [Vorgänge](https://docs.api.europace.de/common/glossary/) of another partner.
      security:
        - europace_oauth2:
            - 'partner:beziehungen:lesen'
    post:
      summary: add access right
      operationId: setUebernahmeRechtFuer
      tags:
        - Partner
        - Rechte
      description: |
        Creates an access right to a partner.

        Example: partner ABC12 is getting the [Zugriffsrecht](https://docs.api.europace.de/common/glossary/) from XYZ56. ABC12 can then access the [Vorgänge](https://docs.api.europace.de/common/glossary/) of XYZ56.

        Requirements:
        * OAuth token has scope `partner:beziehung:schreiben`.
        * Caller has Einstellungsrecht on the partner to which the Zugriffsrecht is added 
        * Caller has Einstellungsrecht on the partner to which the access is granted
      security:
        - europace_oauth2:
            - 'partner:beziehungen:schreiben'
  '/partner/{partnerId}/zugang':
    get:
      summary: get user access
      tags:
        - Partner
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      operationId: getZugang
      description: |-
        Delivers the user access of a partner. 
        In the case of a person, the usernames are supplied. 
        In the case of an organization, the identity provider configuration are supplied.

        Requirements:
        * OAuth token has scope `partner:plakette:lesen`
        * To access a partner, the caller basically needs permission to see it. This right exists if the retrieved partner is below the authenticated partner in the hierarchy or the Einstellungsrecht is assigned to the authenticated partner.
    post:
      summary: create user access
      tags:
        - partner
      operationId: createZugang
      security:
        - europace_oauth2:
            - 'partner:plakette:schreiben'
      description: |-
        Creates an user access for a person.

        A newly created partner needs a [Zugang](https://docs.api.europace.de/common/glossary/) to be able to log in to Europace with username. The Zugang can be created by the settings-frontend (Einstellungen) or the partner-API.

        Requirements for all use cases and examples:
        * OAuth token has scope `partner:plakette:schreiben`
        * To access a partner, the caller basically needs permission to see it. This right exists if the retrieved partner is below the authenticated partner in the hierarchy or the Einstellungsrecht is assigned to the authenticated partner.

        #### Use case 1: Create Europace user.
        The user with the PartnerId:ABC12 is set up an Zugang with the username "max.musterman@example.org" and an activation email (`sendEmail=true`) is sent to the username. In the activation email, the user is prompted to set a password.

        >Note: \
        >The reply address in the activation email is the email or username of the subject in the access-token that created the Zugang.
        >If no email address or username is available, the reply goes to noreply@europace2.de.

        Requirement for use case 1:
        * the username is Europace-wide unique
        * the username is an e-mail address

        #### Use case 2: Create user for own identity provider.
        This use case is most common with banking partners or direct sales organizations where allemployees have a company email with their own domain and the employees work exclusively within this organization.

        In this use case, the partner's identity provider is configured and the username is used as the user identifier at Europace and the partner's identity provider.

        Don't send an activation email (`sendEmail=false`), because the user already exists in the partner's Identity Provider.

        Requirement for use case 2:
        * the username is Europace-wide unique
        * the username is an e-mail address

        #### Use case 3: Username is not unique Europace-wide or no email address 
        A user:in is to be created for the own Identity Provider, but the username is Europace-wide not unique or no e-mail address. In this case the field 'benutzername' is not used at all, but only the field 'identityProviderBenutzername'. The identification of the user on the login mask can only be done via a `partnerId`. The `partnerId` can be passed to the login mask with the `username` parameter in some use cases to improve the user experience.

        Since it is an existing user in the identity provider of the partner and the identityProvider username is only used here, no activation email is sent, regardless of the `sendEmail` parameter.

        Requirements for use case 3:
        * No further
    patch:
      summary: Zugang bearbeiten
      tags:
        - Partner
      operationId: patchZugang
      description: |-
        The [Benutzernamen](https://docs.api.europace.de/common/glossary/) of external identity providers can be changed with Partner API.

        Restriction:
        * the field `benutzername` cannot be changed
components:
  securitySchemes:
    europace_oauth2:
      type: http
      scheme: bearer
      description: ''
security:
  - europace_oauth2: []
