openapi: 3.0.0

info:
  title: partner-api
  version: '2.0-alpha'
  description: 'Das Partnermanagment von Europace ermöglicht Organisationen ihre eigenen Struktur abzubilden, um jedem Partner oder Mitarbeiter einen Zugang zu geben und Rechte einzustellen.'
  contact:
    name: Europace AG
    url: 'http://developer.europace.de'
    email: info@europace.de
  termsOfService: 'https://developer.europace.de/terms/'

servers:
  - url: 'https://api.europace.de/v2'
    description: Produktion Server

paths:
  '/partner/{partnerId}':
    get:
      summary: Lese die Daten eines Partners
      operationId: getPartner
      description: Liefert die Daten eines Partners
      security:
        - europace_oauth2: ['partner:plakette:lesen']
      tags:
        - Partner
    patch:
      summary: Partner anpassen
      operationId: updatePartner
      description: Partner anpassen
      security:
        - europace_oauth2: ['partner:plakette:schreiben']
      tags:
        - Partner

  '/partner/{partnerId}/rechte':
    get:
      summary: Rechte des Partners lesen.
      operationId: getPartnerRechte
      description: Liefert die Rechte eines Partners
      security:
        - europace_oauth2: ['partner:rechte:lesen']
      tags:
        - Partner
    patch:
      summary: Ein Recht eines Partners setzen
      operationId: setPartnerRecht
      description: Alle Rechte eines Partners aktualisieren
      security:
        - europace_oauth2: ['partner:rechte:schreiben']
      tags:
        - Partner
  '/partner/{partnerId}/untergeordnete':
    post:
      summary: Partner erstellen
      operationId: createPartner
      description: 'Erstellt einen neuen Partner als Organisation oder Person, abhängig vom Typ.'
      security:
        - europace_oauth2: ['partner:plakette:anlegen']
      tags:
        - Partner
    get:
      summary: untergeordnete Partner abrufen
      operationId: getChildren
      description: Liefert eine Liste von untergeordneten Partnern.
      security:
        - europace_oauth2: ['partner:plakette:lesen']
      tags:
        - Partner

  '/partner/{partnerId}/partnerkennzeichen':
    get:
      summary: Partnerkennzeichen abrufen
      operationId: getPartnerkennzeichen
      description: Die Partnerkennzeichen identifizieren einen Vertrieb bei einem Produktanbieter. Die erfassten Werte können über diesen Endpunkt ausgelesen werden.
      security:
        - europace_oauth2: ['partner:plakette:lesen']
      tags:
        - Partner
  '/partner/{partnerId}/administrierbare':
    get:
      summary: Alle Plaketten abrufen, auf die der Partner Einstellungsrechte hat.
      operationId: getAdministrierbare
      tags:
        - Partner
      description: |-
        Liefert alle Partner, bei denen dieser Partner die Daten und Berechtigungen ändern oder das Reporting abrufen darf.
        Es wird mindestens der Partner selbst zurückgegeben, da jeder mindestens sich selbst einstellen oder sein eigenes Reporting abrufen darf.
      security:
        - europace_oauth2: ['partner:beziehungen:lesen']
  '/partner/{partnerId}/uebernehmbare':
    get:
      summary: Alle Partner abrufen, auf die der Partner Übernahmerecht hat.
      operationId: getUebernehmbare
      tags:
        - Partner
      description: 'Liefert alle Partner, deren Daten von dem Partner gesehen, geöffnet und bearbeitet werden können (Zugriff). '
      security:
        - europace_oauth2: ['partner:beziehungen:lesen']
  '/partner/{partnerId}/uebernahmeRechtFuer/{target}':
    get:
      summary: Zugriffrecht auf einen bestimmten Partner prüfen
      operationId: getUebernahmeRechtFuer
      tags:
        - Partner
      description: 'Ermittelt, ob der Partner auf die Vorgänge eines anderen Partner zugreifen darf'
      security:
        - europace_oauth2: ['partner:beziehungen:lesen']
components:
  securitySchemes:
    europace_oauth2:
      $ref: 'https://raw.githubusercontent.com/europace/authorization-api/master/europace_security.yaml'
