openapi: 3.0.3
tags:
  - name: Partner
  - name: Rechte
info:
  title: partner-api
  version: v2.0
  description: 'Das Partnermanagment von Europace ermöglicht Organisationen ihre eigenen Struktur abzubilden, um jedem Partner oder Mitarbeiter einen Zugang zu geben und Rechte einzustellen.'
  contact:
    name: Europace AG
    url: 'http://docs.api.europace.de'
    email: info@europace.de
  termsOfService: 'https://docs.api.europace.de/nutzungsbedingungen/'
servers:
  - url: 'https://api.europace.de/v2'
    description: Produktion Server
paths:
  '/partner/{partnerId}':
    get:
      summary: Partnerdaten abrufen
      operationId: getPartner
      description: Liefert die Daten eines Partners
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      tags:
        - Partner
    patch:
      summary: Partner anpassen
      operationId: updatePartner
      description: Partner anpassen
      security:
        - europace_oauth2:
            - 'partner:plakette:schreiben'
      tags:
        - Partner
  '/partner/{partnerId}/rechte':
    get:
      summary: Partner-Rechte abrufen
      operationId: getPartnerRechte
      description: Liefert die Rechte eines Partners
      security:
        - europace_oauth2:
            - 'partner:rechte:lesen'
      tags:
        - Partner
        - Rechte
    patch:
      summary: Partner-Recht setzen
      operationId: setPartnerRecht
      description: Alle Rechte eines Partners aktualisieren
      security:
        - europace_oauth2:
            - 'partner:rechte:schreiben'
      tags:
        - Partner
  '/partner/{partnerId}/untergeordnete':
    post:
      summary: Partner anlegen
      operationId: createPartner
      description: 'Erstellt einen neuen Partner als Organisation oder Person, abhängig vom Typ.'
      security:
        - europace_oauth2:
            - 'partner:plakette:anlegen'
      tags:
        - Partner
    get:
      summary: untergeordnete Partner abrufen
      operationId: getChildren
      description: Liefert eine Liste von untergeordneten Partnern.
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      tags:
        - Partner
        - Rechte
  '/partner/{partnerId}/partnerkennzeichen':
    get:
      summary: Partnerkennzeichen abrufen
      operationId: getPartnerkennzeichen
      description: Die Partnerkennzeichen identifizieren einen Vertrieb bei einem Produktanbieter. Die erfassten Werte können über diesen Endpunkt ausgelesen werden.
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      tags:
        - Partner
  '/partner/{partnerId}/administrierbare':
    get:
      summary: administrierbare Partner abrufen
      operationId: getAdministrierbare
      tags:
        - Partner
        - Rechte
      description: |
        Liefert alle Partner, bei denen dieser Partner die Daten und Berechtigungen ändern oder das Reporting abrufen darf.
        Es wird mindestens der Partner selbst zurückgegeben, da jeder mindestens sich selbst einstellen oder sein eigenes Reporting abrufen darf.

        Um eine bessere Performance zu erreichen, wurde in der neuen PEX2 darauf verzichtet die implizit administrierbaren Partner mit ausgegeben. Um diese zu ermitteln, ist es notwendig über die Untergeordneten der Resultliste zu iterieren.
      security:
        - europace_oauth2:
            - 'partner:beziehungen:lesen'
  '/partner/{partnerId}/uebernehmbare':
    get:
      summary: übernehmbare Partner abrufen
      operationId: getUebernehmbare
      tags:
        - Partner
        - Rechte
      description: |-
        Liefert alle Partner, deren Vorgänge vom Partner gesehen, geöffnet und bearbeitet werden können (Zugriff). 

        Um eine bessere Performancezu erreichen, wurde in der neuen PEX2 darauf verzichtet die implizit Übernehmbaren mit ausgegeben. Um diese zu ermitteln, ist es notwendig über die Untergeordneten der Resultliste zu iterieren.
      security:
        - europace_oauth2:
            - 'partner:beziehungen:lesen'
  '/partner/{partnerId}/uebernahmeRechtFuer/{target}':
    get:
      summary: Übernahmerecht für einen Partner prüfen
      operationId: getUebernahmeRechtFuer
      tags:
        - Partner
        - Rechte
      description: 'Ermittelt, ob der Partner auf die Vorgänge eines anderen Partner zugreifen darf'
      security:
        - europace_oauth2:
            - 'partner:beziehungen:lesen'
    post:
      summary: Zugriffrecht auf einen Partner vergeben
      operationId: setUebernahmeRechtFuer
      tags:
        - Partner
        - Rechte
      description: Erzeugt ein Zugriffsrecht auf einen Partner
      security:
        - europace_oauth2:
            - 'partner:beziehungen:schreiben'
  '/partner/{partnerId}/zugang':
    get:
      summary: Zugang abfragen
      tags:
        - Partner
      security:
        - europace_oauth2:
            - 'partner:plakette:lesen'
      operationId: getZugang
      description: Liefert die Zugangsdaten eines Partners. Bei einer Person werden die Benutzer-Zugangsdaten und bei einer Organisation die Daten des Identity Provider geliefert.
    post:
      summary: Zugang anlegen
      tags:
        - Partner
      operationId: createZugang
      security:
        - europace_oauth2:
            - 'partner:plakette:schreiben'
      description: Erzeugt einen Zugang für eine Person.
    patch:
      summary: ''
      operationId: patchZugang
      description: Ändert Benutzernamen und/oder IdP-Benutzernamen.
components:
  securitySchemes:
    europace_oauth2:
      type: http
      scheme: bearer
      description: ''
security:
  - europace_oauth2: []
