openapi: 3.0.0

info:
  title: partner-api
  version: '2.0.0'
  description: 'Das Partnermanagment von Europace ermöglicht Organisationen ihre eigenen Struktur abzubilden, um jedem Partner oder Mitarbeiter einen Zugang zu geben und Rechte einzustellen.'
  contact:
    name: Europace AG
    url: 'http://developer.europace.de'
    email: info@europace.de
  termsOfService: 'https://developer.europace.de/terms/'

servers:
  - url: 'https://api.europace.de/v2/partnermanagement'
    description: production server
  - url: 'https://api.europace.de/stub/partnermanagement'
    description: test server

paths:
  '/partner/{partnerId}':
    get:
      summary: Read data of a Partner
      operationId: getPartner
      description: Liefert die Daten eines Partners
      security:
        - europace_oauth2: ['partner:entity:read']
      tags:
        - Partner
    patch:
      summary: Partner anpassen
      operationId: updatePartner
      description: Partner anpassen
      security:
        - europace_oauth2: ['partner:entity:write']
      tags:
        - Partner

  '/partner/{partnerId}/rechte':
    get:
      summary: Rechte des Partners lesen.
      operationId: getPartnerRechte
      description: Liefert die Rechte eines Partners
      security:
        - europace_oauth2: ['partner:rechte:read']
    patch:
      summary: Ein Recht eines Partners setzen
      operationId: setPartnerRecht
      description: Alle Rechte eines Partners aktualisieren
      security:
        - europace_oauth2: ['partner:rechte:write']
  '/partner/{partnerId}/untergeordnetePartner':
    post:
      summary: Partner erstellen
      operationId: createPartner
      description: 'Erstellt einen neuen Partner als Organisation oder Person, abhängig vom Typ.'
      security:
        - europace_oauth2: ['partner:entity:create']
      tags:
        - Partner
    get:
      summary: untergeordnete Partner abrufen
      operationId: getChildren
      description: Liefert eine Liste von untergeordneten Partnern.
      security:
        - europace_oauth2: ['partner:entity:read']
      tags:
        - Partner

  '/partner/{partnerId}/partnerkennzeichen':
    get:
      summary: Partnerkennzeichen abrufen
      operationId: getChildren
      description: Die Partnerkennzeichen identifizieren einen Vertrieb bei einem Produktanbieter. Die erfassten Werte können über diesen Endpunkt ausgelesen werden.
      security:
        - europace_oauth2: ['partner:entity:read']
      tags:
        - Partner
  '/partner/{partnerId}/administrierbare':
    get:
      summary: Alle Plaketten abrufen, auf die der Partner Einstellungsrechte hat.
      tags:
        - Partner
      description: |-
        Liefert alle Partner, bei denen dieser Partner die Daten und Berechtigungen ändern oder das Reporting abrufen darf.
        Es wird mindestens der Partner selbst zurückgegeben, da jeder mindestens sich selbst einstellen oder sein eigenes Reporting abrufen darf.
      security:
        - europace_oauth2: ['partner:relationships:read']
  '/partner/{partnerId}/uebernahmeRechtFuer':
    get:
      summary: Alle Partner abrufen, auf die der Partner Übernahmerecht hat.
      tags:
        - Partner
      description: 'Liefert alle Partner, deren Daten von dem Partner gesehen, geöffnet und bearbeitet werden können (Zugriff). '
      security:
        - europace_oauth2: ['partner:relationships:read']
  '/partner/{partnerId}/uebernahmeRechtFuer/{partnerId2}':
    get:
      summary: Zugriffrecht auf einen bestimmten Partner prüfen
      tags:
        - Partner
      description: 'Ermittelt, ob der Partner auf die Vorgänge eines anderen Partner zugreifen darf'
      security:
        - europace_oauth2: ['partner:relationships:read']
components:
  securitySchemes:
    europace_oauth2:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials flow. [More info](https://auth0.com/docs/flows/concepts/client-credentials)
      flows:
        clientCredentials:
          tokenUrl: https://api.europace.de/auth/token
          scopes:
            partner:entity:create: Create a new Partner entity
            partner:entity:delete: Delete the whole Partner
            partner:entity:read: Read partner data
            partner:entity:write: Modify data of a partner
            partner:relationships:read: Read relationships between partners
            partner:relationships:write: Modify relationships between partners
            partner:rechte:read: Read Rechte eines Partners
            partner:rechte:write: Schreibe Rechte eines Partners
